language: java

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:https | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.5-bin.tar.gz
  - tar -xzvf apache-ant-1.10.5-bin.tar.gz
  - export PATH=`pwd`/apache-ant-1.10.5/bin:$PATH
  - echo $(ant -version)

install:
  - chmod -R 755 lib/junit/

script:
  - ant -lib lib/junit/junit-4.12.jar:lib/junit/junit-jupiter-api-5.3.2.jar:lib/junit/junit-jupiter-engine-5.3.2.jar:lib/junit/junit-jupiter-params-5.3.2.jar:lib/junit/junit-platform-commons-1.3.2.jar:lib/junit/junit-platform-engine-1.3.2.jar:lib/junit/junit-platform-launcher-1.3.2.jar:lib/junit/junit-vintage-engine-5.3.2.jar:lib/junit/opentest4j-1.0.0.jar

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "D+Shdubv0/f++hp5BTjjx++kq3k0zqvWB0kISmZM8SiVseV6KLgw8lCaW9IDixguIqAKlMsgaeEPDI9HXcFwI+D/Cl40pMeR56svn8mWr0vNJFSQO07RIDeaMOnQ5C05bngbjKDd/4GOHbOqAUz3bLscQIc3HAnL/InrR0YPeM2mSz3ZyfwIyXX14WhgXH2bwLVzOBdGBB7qbJ8qRKVsrr1t+5Gj34BfUuLwvN8Nl6Ym0jlgKg0jzyy8/FblXdDbEW0cwhhFK0rgRUHdhq/1AKo0r+LkF5pi8zHbBcMm1YFG1g7SA/tQ1vqtUH8QAOR4XNd8yPbiOeCAC3TGgO2nsChYIgGqyt7ScOogJ9z5KLuujjhDaZ2qfEZaClGogYudBIVtnFNtgSxT7uPbiGcUM6AbjVmc+KCI7rMtPnxGYNdr4iwiO11so3EWVuWOaX/jKdfahoWcPq8X9+miidHR1UUieL4TeXtO26/Ck9orcZZtDczh2EnHDcLcJvESrKel1bb40SqnGZyDsUQruQ8UVXMbFMj+LHwHm6ugpZfo6PXYYo6QH4N/erU5DX4wgmW4f3Di9oGdWtEkoMeQPdxEMh0uHQh+0Er0SXsT3ZTbCSV/2jlgkygOtwnKbHBIu4W79XcjypWDzWa4/bFShuMB+dCN+mJxmfl8dAwKW7umq54="

addons:
  coverity_scan:
    project:
      name: "TUDa-BP-11/opendiabetes-uam-heuristik"
      description: "Build submitted via Travis CI"
    notification_email: bachelor-praktikum-gruppe-11@googlegroups.com
    build_command_prepend: "<Your build preprocessing command here>"
    build_command: ant -buildfile code/OpenDiabetesVault-Engine/build.xml 
    branch_pattern: coverity_scan
