language: java

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:https | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.5-bin.tar.gz
  - tar -xzf apache-ant-1.10.5-bin.tar.gz
  - export PATH=`pwd`/apache-ant-1.10.5/bin:$PATH
  - echo $(ant -version)
  - nvm install 10.15.3

install:
  - chmod -R 755 lib/junit/
  - ant -lib lib/junit all-compile
  - bash install-nightscout.sh

script:
  - ant -lib lib/junit all-test

after_script:
  - cat code/*/dist/TEST-*.txt

after_failure:
  - cat cgm-remote-monitor/server.log

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: D+Shdubv0/f++hp5BTjjx++kq3k0zqvWB0kISmZM8SiVseV6KLgw8lCaW9IDixguIqAKlMsgaeEPDI9HXcFwI+D/Cl40pMeR56svn8mWr0vNJFSQO07RIDeaMOnQ5C05bngbjKDd/4GOHbOqAUz3bLscQIc3HAnL/InrR0YPeM2mSz3ZyfwIyXX14WhgXH2bwLVzOBdGBB7qbJ8qRKVsrr1t+5Gj34BfUuLwvN8Nl6Ym0jlgKg0jzyy8/FblXdDbEW0cwhhFK0rgRUHdhq/1AKo0r+LkF5pi8zHbBcMm1YFG1g7SA/tQ1vqtUH8QAOR4XNd8yPbiOeCAC3TGgO2nsChYIgGqyt7ScOogJ9z5KLuujjhDaZ2qfEZaClGogYudBIVtnFNtgSxT7uPbiGcUM6AbjVmc+KCI7rMtPnxGYNdr4iwiO11so3EWVuWOaX/jKdfahoWcPq8X9+miidHR1UUieL4TeXtO26/Ck9orcZZtDczh2EnHDcLcJvESrKel1bb40SqnGZyDsUQruQ8UVXMbFMj+LHwHm6ugpZfo6PXYYo6QH4N/erU5DX4wgmW4f3Di9oGdWtEkoMeQPdxEMh0uHQh+0Er0SXsT3ZTbCSV/2jlgkygOtwnKbHBIu4W79XcjypWDzWa4/bFShuMB+dCN+mJxmfl8dAwKW7umq54=
    # variables for cgm-remote-monitor server
    - MONGO=mongodb://127.0.0.1:27017/nightscout
    - HOSTNAME=localhost
    - PORT=8000
    - API_SECRET=MySuperDuperSecret
    - ENABLE="careportal iob cob openaps pump bwg rawbg basal uam"
    - INSECURE_USE_HTTP=true
    # Nightscout host for testing
    - NS_HOST=http://$HOSTNAME:$PORT
    # Nightscout api secret for testing
    - NS_APISECRET=$API_SECRET
    # Nightscout host for synchronizer testing: $NS_HOST_2
    - secure: cZHomUkWps9AXlMCZcrCZc2bv05fnc4hLGGwyU7eFA1bXNofLvrhOUdBpjZp1BaQgDVn0uG5bjXBC034DLwNfbx9DPW/NHiU9PPnP5VgAjOrxRRw3uCFPctsL0mjnywQiKw8S+IXaXvkGhGFWt0BZ/LgmezhsqKV+EYVBjxgMPD4AbnX4nTwqQHpCF00T3R93aoz+KOMz2PSmcC32oK6R1PiRQIKpa0K7QMExfKAcIOPLNUJmPiMoe2w6DdW+NwvFVGOHOZ2B0Eoc2F0of0/808OOLZVrH2vnecSmvEtRGz+8BxuVpZnNwzOnjIVuxTdnHgxFxZMgOoVoRBl0EtpVRehoUzmcdgBVMCJz/i0NOULr8cOiof7DidFQdrP497fJEMFI+waRCxbGj2IvqsVGdeIwaRVqcKcpV2oPZ2FIN+FqbVEyrIZ20qQkOiG4HalZ7r3i+mSreS7FYGCrfzNTnFqBv9LM3Qoo7tOUjoSAl81IdOMdyqDYjBjnz4pCtQhPvYBpWecL9HJ3UWLWPkrKM0+p0PyWcImXKWvXiJ1gR+smT7kH328Hx/ZzhzLap8c3/SV1xvC+buX3n94ZBjkIs+tquRx3VQAq/UZIQdOyHgQxDa9bgalCIucQNVtHRLebXCFVoXk/uL/ZZ0/4reWj86t8/Cu4cZYh6GKzAh7BkA=
    # Nightscout api secret for synchronizer testing: $NS_APISECRET_2
    - secure: LLago1PUve8wvJbprUj+nGieejGZ5TBJqD3owl4VK8GMvvlYFxbrTiuo9/pcVKxtMgtTVfz9TFbtzZuKQajfQDwhpSNlgYCfcsf4PijvpiflkDW7eAfd5AvqViYBrDGO93x/U8clyy7AmXWOuYT55ktKDVHHnPi4JCGlj/7tnB5KKkmva3ySwKfrIvnYF9XfUQkJKIRnWqcr8hv1dLxtfYpKSIUVyMa/x1XdTDoR1OFHqfVxKQHp8xr908ak5U3LHbwvoDzYwyxJ1z0WVzZ+OyfIedeYXH20XVN5j+3pCkT+7ZUCZDzua6bj7cy9jkrliXbqb1nZRdrslTiRo9LqP6RKTBK1C+jGzwrPVnR7txTU+fkanCXALIWmrvONPA2ViZPUkv6zugX/AbqGjr7NSsLUvwBxrW9P04HHmisPJLtY/Az9P7nCMMe4v3kaEjQjilDG+jLDzmU0fsdScG3/++hrVB/Wj49VPqMLAx+q+167v7jBd4AfnIpN8wQiPpDaUpQksFTzxSpD4VvcLlpbBBZ+I9IfOlr/fCivvr20ioR6cSd/qX7IVoCxrGOB5xgeQz+xIyITTT6mJely9jt93f3d0EC+aR/vQO5waiL/ff2sCObslpndI4yox8XBdWmFy0x+60fiUvmX3IMnq4Y6X3CgHG2pw/kaVmuKZkwdj2o=

addons:
  coverity_scan:
    project:
      name: "TUDa-BP-11/opendiabetes-uam-heuristik"
      description: "Build submitted via Travis CI"
    notification_email: bachelor-praktikum-gruppe-11@googlegroups.com
    build_command_prepend: ""
    build_command: ant -lib lib/junit all-compile
    branch_pattern: coverity_scan

services: mongodb
